### ISSUE TITLE
引入 opensea-js 時出現問題

### ISSUE THREAD

**Issue by shingo0620** [chnejohnson/vue3-dapp-starter#1]
按照 opensea-js doc 只放了一行
`import { OpenSeaPort, Network } from 'opensea-js'`

就報錯了
`
Uncaught TypeError: Object prototype may only be an Object or null: undefined
    at Function.create (<anonymous>)
    at Object.inherits (inherits_browser.js:6:31)
    at node_modules/level-iterator-stream/node_modules/readable-stream/lib/_stream_readable.js (_stream_readable.js:63:6)
    at __require2 (chunk-JUD4L4V5.js?v=cce9e3a6:36:44)
    at node_modules/level-iterator-stream/node_modules/readable-stream/readable.js (readable.js:1:28)
    at __require2 (chunk-JUD4L4V5.js?v=cce9e3a6:36:44)
    at node_modules/level-iterator-stream/index.js (index.js:2:16)
    at __require2 (chunk-JUD4L4V5.js?v=cce9e3a6:36:44)
    at node_modules/levelup/lib/levelup.js (levelup.js:13:22)
    at __require2 (chunk-JUD4L4V5.js?v=cce9e3a6:36:44)
`

code 在 https://github.com/shingo0620/vue3-dapp-starter
不知道大大有沒有什麼頭緒Orz

**Comment by chnejohnson** [comment]
不太清楚，可能是 opensea-js 的 Type 檢查錯了，還是跟 ethers.js 不相容，https://github.com/ProjectOpenSea/opensea-js/issues/28。

**Comment by shingo0620** [comment]
@chnejohnson  這是我正在玩的專案 [ChronoCats](https://chronocats.com)
原本是用 vite+vue3 開發的好好的..結果在引入 opensea-js 打算做快速購買才發現..build production的時候polyfill有點狀況Orz...一堆process, Buffer, path 什麼的 nodejs lib 沒有辦法一起build進去 (可是 yarn dev 的時候設定好就ok 沒這個困擾)

花了三天還是搞不定一氣之下只好用 vue-cli 來處理...可是還是想試著找看看解決的方法..用 vite 開發真的太吸引人了

**Comment by chnejohnson** [comment]
@shingo0620 你說的 vite  的問題也讓我很頭痛，我覺得用 vue-cli 來處理真的可以少一點煩惱，雖然 vite 用起來很快很乾淨，但一出問題真的是修不完解不開，然後我覺得作者也不想處理這個問題...
https://github.com/vitejs/vite/issues/728#issuecomment-767168681

**Comment by shingo0620** [comment]
感謝回覆...可以心死的用 vue-cli 繼續走下去了..
